<?php
/**
 * This file is part of the PlusClouds.Core library.
 *
 * (c) Semih Turna <semih.turna@plusclouds.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace PlusClouds\Core\Database\Observers;

use Illuminate\Database\Eloquent\Model;
use PlusClouds\Core\Database\Models\Domain;

/**
 * Class DiscountObserver
 * @package PlusClouds\Core\Database\Observers
 */
class DomainObserver extends AbstractObserver
{
    public function creating(Model $model)
    {
        $domain = $model->name;

        $exploded = explode('.', $domain);

        $domain = '';

        for ($i = (count($exploded) - 1) ; $i > 0; $i--) {
            $domain = $exploded[$i] . $domain;

            if (! Domain::where('name', $domain)->first()) {
                Domain::create([
                    'name' => $domain
                ]);
            }

            $domain = '.' . $domain;
        }

        parent::creating($model); // TODO: Change the autogenerated stub
    }

    public function created(Model $model)
    {
        parent::created($model); // TODO: Change the autogenerated stub
    }
}
