<?php
/**
 * This file is part of the PlusClouds.Core library.
 *
 * (c) Semih Turna <semih.turna@plusclouds.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace PlusClouds\Core\Database\Observers;

use Illuminate\Database\Eloquent\Model;
use PlusClouds\Core\Events\DomainCreated;

/**
 * Class DiscountObserver
 * @package PlusClouds\Core\Database\Observers
 */
class DomainObserver extends AbstractObserver
{
    public function creating(Model $model)
    {
        parent::creating($model); // TODO: Change the autogenerated stub
    }

    public function created(Model $model)
    {
		event(new DomainCreated($model));

		logger()->info('[Observer\Domain] Domain Created.');

        parent::created($model); // TODO: Change the autogenerated stub
    }
}
